export const arsenal = [
	{
        id: 0,
        number: 1,
		name: "cebollurl",
        description: "O bolbo faminto por carne",
		class: ["Flora", "Water"],
		stats: {hp: 84, atk: 87, def: 100, spe: 59},
	},
    {
        id: 1,
        number : 2,
		name: "oniette",
        description: "A bolbo de corte rápido",
		class: ["Flora", "Water"],
		stats: {hp: 60, atk: 127, def: 73, spe: 70},
	},
    {
        id: 2,
        number: 3,
		name: "rei cebollurl",
        description: "O líder da horda de bolbos devoradores",
		class: ["Flora", "King"],
        stats: {hp: 124, atk: 151, def: 143, spe: 107},
    },
    {
        id: 3,
        number: 4,
		name: "rei oniette",
        description: "A líder da horda de bolbos caçadores de larvas",
		class: ["Flora", "King"],
        stats: {hp: 110, atk: 180, def: 100, spe: 160},
    },
    {
        id: 4,
        number: 5,
		name: "rasputin",
        description: "O pairador de águas profundas",
		class: ["Water"],
        stats: {hp: 157, atk: 100, def: 168, spe: 100},
    },
    {
        id: 5,
        number: 6,
		name: "ange",
        description: "A tormenta florestal",
		class: ["Tormented"],
        stats: {hp: 90, atk: 187, def: 100, spe: 148},
    },
    {
        id: 6,
        number: 7,
		name: "marry",
        description: "A drúida ancestral",
		class: ["Witch"],
        stats: {hp: 200, atk: 106, def: 100, spe: 119},
    },
    {
        id: 7,
        number: 8,
		name: "serena",
        description: "A cepa letal",
		class: ["Virus"],
        stats: {hp: 166, atk: 120, def: 92, spe: 147},
    },
    {
        id: 8,
        number: 9,
		name: "northon",
        description: "O dobrador de infernos",
		class: ["Fire", "King"],
        stats: {hp: 105, atk: 135, def: 180, spe: 105},
    },
    {
        id: 9,
        number: 10,
		name: "miguel",
        description: "O espectro primata",
		class: ["Fire", "Flora"],
        stats: {hp: 102, atk: 175, def: 73, spe: 175},
    },
    {
        id: 10,
        number: 11,
		name: "caronte",
        description: "O analista do caos",
		class: ["King", "Water"],
        stats: {hp: 136, atk: 142, def: 93, spe: 154},
    }
]